### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by MaximilianLloyd** [wooorm/plain-text-data-to-json#1]
A cli would be very much appreciated

**Comment by wooorm** [comment]
Most definitely! I, however don’t have the time. So, if you do, please give it a shot (it’ll be greatly appreciated).

P.S. I’d suggest it to be a different module / project.

**Comment by MaximilianLloyd** [comment]
Sure thing. i have some free time this weekend so don't see why not :)

**Comment by wooorm** [comment]
Awesome! That be so cool. Ping for a little help, but I think most should be straightforward :smile:

**Comment by MaximilianLloyd** [comment]
Made a CLI https://github.com/MaximilianLloyd/text-to-json-cli/ :)
